In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.cluster._kmeans

In [218]:
df = pd.read_csv("cStick.csv")
df.columns = ['Distance', 'Pressure', 'HRV', 'Sugar level', 'SpO2', 'Accelerometer','Decision']
y = df['Decision']
df = df.drop('Decision', axis=1)
df = df.drop('Pressure', axis=1)
df.head()

Distance      HRV  Sugar level    SpO2  Accelerometer
0    25.540  101.396       61.080  87.770            1.0
1     2.595  110.190       20.207  65.190            1.0
2    68.067   87.412       79.345  99.345            0.0
3    13.090   92.266       36.180  81.545            1.0
4    69.430   89.480       80.000  99.990            0.0

In [219]:
km = sklearn.cluster._kmeans.KMeans(n_clusters=3)
clusters = km.fit_predict(df)
df['Cluster'] = clusters

/opt/homebrew/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [226]:
print("NMI: ",sklearn.metrics.normalized_mutual_info_score(y, clusters))
# visualize clustering using confusion  matrix
print("Confusion-Matrix: ",'\n',sklearn.metrics.confusion_matrix(y, clusters))




NMI:  0.7411635393979202
Confusion-Matrix:  
 [[  0 690   0]
 [682   0   0]
 [339   0 328]]
