In [259]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix


In [260]:
# create a linear model and test it on the data
def linear_model(x, y):
    # create a linear model
    model = LinearRegression()
    # fit the model to the data
    model.fit(x, y)
    # return the model
    return model

# create a polynomial model and test it on the data
def polynomial_model(x, y, degree):
    # create a polynomial model
    model = np.poly1d(np.polyfit(x, y, degree))
    # return the model
    return model

# import data and split into training and testing data
df = pd.read_csv("cStick.csv")
df.columns = ['Distance', 'Pressure', 'HRV', 'Sugar level', 'SpO2', 'Accelerometer','Decision']
y = df['Decision']
X = df
X = X.drop('Decision', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [263]:
# run linear model
linear = linear_model(X_train, y_train)
# run polynomial model
# polynomial = polynomial_model(X_train, y_train, 3)
# test models
y_pred = linear.predict(X_test)
# y_pred_poly = polynomial.
# print the mean squared error
print('Linear Model Mean Squared Error:', mean_squared_error(y_test, y_pred))
# accuracy of linear model
print('Accuracy of linear model: ', linear.score(X_test, y_test))

# confusion matrix for linear model
y_pred = np.round(y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)
# print('Polynomial Model Mean Squared Error:', mean_squared_error(y_test, y_pred_poly))


Linear Model Mean Squared Error: 1.8398120427311192e-29
Accuracy of linear model:  1.0
[[142   0   0]
 [  0 128   0]
 [  0   0 138]]
